//! Deriving a workload identity from the client certificate presented at the TLS layer.

use std::collections::HashMap;
use std::sync::{Arc, RwLock};

use tonic::Status;
use x509_parser::extensions::{GeneralName, ParsedExtension};
use x509_parser::prelude::{FromDer, X509Certificate};

/// Beyond this many distinct client certificates the cache is cleared rather than grown.
/// A handful of workloads is the expected case; an unbounded map keyed by attacker-
/// supplied certificates would be a memory-growth vector, and rebuilding a few entries
/// is far cheaper than the alternative.
const MAX_CACHED_IDENTITIES: usize = 1024;

/// Resolves certificates to identities, memoized.
///
/// Parsing X.509 on every request would be pure waste inside a 2 ms budget: the same
/// handful of certificates recur for the life of every connection. The cache is keyed by
/// the raw leaf DER, so two different certificates can never collide onto one identity.
#[derive(Default)]
pub struct IdentityExtractor {
    cache: RwLock<HashMap<Vec<u8>, Arc<str>>>,
}

impl IdentityExtractor {
    pub fn new() -> Self {
        Self::default()
    }

    /// Identity of the caller, or an error if none can be established.
    ///
    /// Absence of a certificate is `unauthenticated`, not a fallback to anonymous: the
    /// server requires client auth at the TLS layer, so reaching a handler without one
    /// means something is misconfigured, and guessing would be the wrong response.
    pub fn identify<T>(&self, request: &tonic::Request<T>) -> Result<Arc<str>, Status> {
        let certs = request.peer_certs().ok_or_else(|| {
            Status::unauthenticated("no client certificate presented; mTLS is required")
        })?;

        let leaf = certs
            .first()
            .ok_or_else(|| Status::unauthenticated("empty client certificate chain"))?;
        let der = leaf.as_ref();

        if let Some(identity) = self
            .cache
            .read()
            .ok()
            .and_then(|cache| cache.get(der).cloned())
        {
            return Ok(identity);
        }

        let identity: Arc<str> = parse_identity(der)?.into();

        if let Ok(mut cache) = self.cache.write() {
            if cache.len() >= MAX_CACHED_IDENTITIES {
                cache.clear();
            }
            cache.insert(der.to_vec(), Arc::clone(&identity));
        }

        Ok(identity)
    }
}

/// Pull the workload identity out of a DER certificate.
///
/// The URI SAN is authoritative. Common Name is accepted only as a fallback and warns,
/// because CN has been deprecated as an identity carrier since RFC 2818 and carries no
/// structure -- two unrelated issuers can mint the same CN.
fn parse_identity(der: &[u8]) -> Result<String, Status> {
    let (_, cert) = X509Certificate::from_der(der).map_err(|e| {
        tracing::warn!(error = %e, "client certificate did not parse");
        Status::unauthenticated("client certificate could not be parsed")
    })?;

    for extension in cert.extensions() {
        if let ParsedExtension::SubjectAlternativeName(san) = extension.parsed_extension() {
            for name in &san.general_names {
                if let GeneralName::URI(uri) = name {
                    return Ok((*uri).to_string());
                }
            }
        }
    }

    if let Some(cn) = cert.subject().iter_common_name().next() {
        if let Ok(cn) = cn.as_str() {
            tracing::warn!(
                common_name = cn,
                "client certificate has no URI SAN; falling back to Common Name. \
                 Issue certificates with a SPIFFE URI SAN instead."
            );
            return Ok(cn.to_string());
        }
    }

    Err(Status::unauthenticated(
        "client certificate carries neither a URI SAN nor a Common Name",
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_garbage_certificate() {
        assert!(parse_identity(b"not a certificate").is_err());
    }

    /// The certificates the test suite runs against are generated by
    /// scripts/gen-certs.sh, so this only runs when they are present.
    #[test]
    fn reads_uri_san_from_generated_cert() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../certs/payments.crt");
        let Ok(pem) = std::fs::read(path) else {
            eprintln!("skipping: run scripts/gen-certs.sh first");
            return;
        };

        let (_, pem) = x509_parser::pem::parse_x509_pem(&pem).expect("valid PEM");
        let identity = parse_identity(&pem.contents).expect("identity extracted");
        assert_eq!(identity, "spiffe://local/ns/default/sa/payments");
    }
}
