#!/bin/sh
# Generate the .env that docker-compose reads, with random PINs.
#
# plan.md 9 lists committed PINs as a headline risk, so compose has no PIN defaults
# and hard-fails without this file. Idempotent: an existing .env is left untouched
# so PINs stay stable across runs (regenerating them would orphan the token).
set -eu

ENV_FILE="${1:-.env}"

if [ -f "${ENV_FILE}" ]; then
    echo "${ENV_FILE} already exists; leaving it alone"
    exit 0
fi

rand() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 24; }

cat > "${ENV_FILE}" <<INNER
# Generated by scripts/gen-env.sh. Gitignored -- never commit this file.
#
# These PINs protect a SoftHSM2 *software* token used for local development.
# SoftHSM2 is not an HSM: the key material sits in files on disk, protected by
# filesystem permissions. Do not reuse these values anywhere that matters.
TOKEN_LABEL=grpc-low-latency
SO_PIN=$(rand)
USER_PIN=$(rand)
INNER

chmod 600 "${ENV_FILE}"
echo "wrote ${ENV_FILE} with freshly generated PINs"
